language: node_js
node_js:
  - "stable"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
cache:
  directories:
  - node_modules
script:
  - npm test -- --coverage
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"